on:
  workflow_dispatch:
  push:
  
permissions:
  content: write

jobs:
  precache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwsh -Command Install-Module -Name AWS.Tools.Transcribe -Force
      - uses: github/codespaces-precache@v1-stable
        with:
          regions: WestUs2
          sku_name: standardLinux32gb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
