on:
  workflow_dispatch:
  push:
  
permissions:
  contents: write

jobs:
  precache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PowerShell modules
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          Install-Module -Name AWS.Tools.TranscribeService -Force
      - name: Install Microsoft Visual Studio Code extensions
        run: |
          code --install-extension 4ops.packer
          code --install-extension 4ops.terraform
          code --install-extension amazonwebservices.aws-toolkit-vscode
          code --install-extension arcticicestudio.nord-visual-studio-code
          code --install-extension cweijan.vscode-autohotkey-plus
          code --install-extension daylerees.rainglow
          code --install-extension donjayamanne.githistory
          code --install-extension DotJoshJohnson.xml
          code --install-extension dracula-theme.theme-dracula
          code --install-extension eamodio.gitlens
          code --install-extension EliverLara.andromeda
          code --install-extension Equinusocio.vsc-community-material-theme
          code --install-extension Equinusocio.vsc-material-theme
          code --install-extension equinusocio.vsc-material-theme-icons
          code --install-extension felipe-mendes.slack-theme
          code --install-extension formulahendry.code-runner
          code --install-extension GitHub.codespaces
          code --install-extension gitpod.gitpod-desktop
          code --install-extension gitpod.gitpod-remote-ssh
          code --install-extension hbenl.vscode-test-explorer
          code --install-extension icsharpcode.ilspy-vscode
          code --install-extension iliazeus.vscode-ansi
          code --install-extension influxdata.flux
          code --install-extension johnpapa.vscode-peacock
          code --install-extension kenhowardpdx.vscode-gist
          code --install-extension littlefoxteam.vscode-python-test-adapter
          code --install-extension ms-azuretools.vscode-azurefunctions
          code --install-extension ms-azuretools.vscode-azureresourcegroups
          code --install-extension ms-azuretools.vscode-docker
          code --install-extension ms-dotnettools.csharp
          code --install-extension ms-dotnettools.vscode-dotnet-runtime
          code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
          code --install-extension ms-python.python
          code --install-extension ms-python.vscode-pylance
          code --install-extension ms-toolsai.jupyter
          code --install-extension ms-toolsai.jupyter-keymap
          code --install-extension ms-toolsai.jupyter-renderers
          code --install-extension ms-vscode-remote.remote-containers
          code --install-extension ms-vscode-remote.remote-ssh
          code --install-extension ms-vscode-remote.remote-ssh-edit
          code --install-extension ms-vscode-remote.remote-wsl
          code --install-extension ms-vscode.azure-account
          code --install-extension ms-vscode.cpptools
          code --install-extension ms-vscode.powershell
          code --install-extension ms-vscode.test-adapter-converter
          code --install-extension ms-vsliveshare.vsliveshare
          code --install-extension Nuuf.theme-hackershaze
          code --install-extension octref.vetur
          code --install-extension oderwat.indent-rainbow
          code --install-extension redhat.vscode-commons
          code --install-extension redhat.vscode-yaml
          code --install-extension ritwickdey.LiveServer
          code --install-extension RobbOwen.synthwave-vscode
          code --install-extension samrapdev.outrun
          code --install-extension TabNine.tabnine-vscode
          code --install-extension Unity.unity-debug
          code --install-extension usernamehw.errorlens
          code --install-extension vscodevim.vim
          code --install-extension webrender.synthwave-x-fluoromachine
          code --install-extension ymotongpoo.licenser
      - uses: github/codespaces-precache@v1-stable
        with:
          regions: WestUs2
          sku_name: standardLinux32gb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
