on:
  workflow_dispatch:
  push:
  
permissions:
  contents: write

jobs:
  precache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PowerShell modules
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          Install-Module -Name AWS.Tools.TranscribeService -Force
      - uses: github/codespaces-precache@v1-stable
        with:
          regions: WestUs2
          sku_name: standardLinux32gb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
